### ISSUE TITLE
Cannot select Local ip to Bind when using VPN

### ISSUE THREAD

**Issue by orbypunk** [lunyx/CasualMeter#84]
Hi, ever since the latest update, the option to bind to my local ip has disappeared from the casualmeter window. I have already selected to use raw sockets instead of WinPcap. The drop down window however is not present. I have tried uninstalling/reinstalling and even extracting the casualmeter-master folder into the main folder as suggested but none of these measures have restored the drop-down window. Is there any way to fix this?

**Comment by lunyx** [comment]
It should work automatically now without selecting it.

**Comment by orbypunk** [comment]
That is really odd, since the latest update, i have been unable to use the meter as it does not detect the server as I enter the game using WTFast anymore. Nothing has changed since then. The server IPs i use are still the same as ever, and I run casualmeter as administrator and disabled all firewalls. However, nothing I do actually fixes the issue. Note: Shinrameter works perfectly fine, so I don't think my computer settings are the cause of the problem.

**Comment by lunyx** [comment]
@Gl0 I believe you made this change.  Can you share any info on this issue?

**Comment by Gl0** [comment]
Copy-pasted code was not working.
Fixed.

**Comment by Gl0** [comment]
Btw. Changed logic, overridden servers now does not replace original servers in the list if they have same IP. This is done to preserve serverid from server.txt. But this does not break the ability to add vpn's, which is the main purpose of servers-overrides.

**Comment by orbypunk** [comment]
Hm thanks for the update. It's still not working though, really cant figure out why....

**Comment by lunyx** [comment]
I haven't sent out the release yet.

**Comment by kronusgarcia** [comment]
I cant use casual with vpn =(

**Comment by Gl0** [comment]
Recheck that you are using raw sockets mode, running meter as admin, have set up firewall exception for the meter (using full path without macros like %Desktop%), and have correct ip address and region in [servers-overrides.txt](https://github.com/lunyx/CasualMeter/wiki/Settings-(Advanced)#server-overridestxt)

**Comment by happikush** [comment]
I'm using v1.2.0.2 and got stuck on Step 5 of [VPN-guide](https://github.com/lunyx/CasualMeter/wiki/Using-VPN's).
I don't see the setting mentioned in Step 5, has this been removed?

Also when specifying the server name in [server-override-guide](https://github.com/lunyx/CasualMeter/wiki/Settings-%28Advanced%29#server-overridestxt), where should I get the format for it? (i.e. If I'm using Wtfast.)  And is it case sensitive?

**Comment by Gl0** [comment]
Server name from this file is seen only for few seconds before receiving of actual server id from game packets. You may write there any string.

**Comment by happikush** [comment]
Not what I wanted to read. :) Was hoping the server name was the problem. But yea I still can't get it to work through Wtfast.

Did all that was instructed in VPN-Guide and server-override-guide.
Just to be sure, the IP Address I need to add from Resource Monitor is the one under Remote Address right?

If it matters I run the programs in this order WTFast > CasualMeter > Tera.

**Comment by Gl0** [comment]
yes

**Comment by happikush** [comment]
I setup my WTFast as manual select, and I only use 1 server. Plus during my tests with CasualMeter I didn't change/restart WTFast. Monitored the Remote Address for WTFast and it didn't change either.

I only restarted the Tera Client and CasualMeter during my tests. Restarted CasualMeter each time I edited server-overrides.txt. Also not sure if it matters but line endings for server-overrides.txt is Unix based? Opening server-overrides.txt in Notepad makes it a 1-liner.

Other than those didn't notice anything strange, I can provide logs or other infos if you plan on debugging it further.

**Comment by Gl0** [comment]
recheck incoming firewall rules

**Comment by happikush** [comment]
LOL. Ok failed hard on that one. I erroneously added the exe for v1.2.0.1 in firewall. My bad for that. (There any reason that still exists? This was my first time to install CasualMeter and it placed 2 versions in my AppData.)

Anyway @orbypunk I got it to work through WTFast. I hope it helps, but I added another IP Address to server-overrides.txt. This IP, also used by WTFast, only appears in Resource Monitor when you launch Tera client too. (Running WTFast alone you can see Remote Address it uses for port 80 and 443 only.)

So yea, I tested it by removing that IP, and CasualMeter didn't work again.
@Gl0 thanks again mate! Awesome to see it working. :+1:

**Comment by kronusgarcia** [comment]
@happikush the WTFast shows only 3 remote address, do u put all 3 in server-overrides? and how do u past "IP NA Servergame?(MT, VOT?)"

**Comment by Gl0** [comment]
You don't need to add remote addresses used by wtfast, you need addresses used by tera.exe... (if you choose static server in wtfast - it should be the only one).
You need to add something like 
`1.2.3.4 NA wtfast`

**Comment by kronusgarcia** [comment]
I use Noping Elite, and when i see the address from tera.exe is loopback IPv4.. And i have a from TCPVIEW show me 2 ips from noping elite

**Comment by Gl0** [comment]
If it's loopback - write loopback. 
`127.0.0.1 NA ssh-vpn`
We need to capture unencrypted traffic between tera client and proxy, not encrypted traffic between proxy and it's uplink server.
Many ssh-tunneling proxy use such method.
I've tested it with wowping.ru, that is using same technique - meter is working fine.

**Comment by kronusgarcia** [comment]
so if it is loopback i use 127.0.0.1 NA ssh-vpn?

**Comment by Gl0** [comment]
If you are playing on NA servers - yes

**Comment by kronusgarcia** [comment]
ok.. ill try now

**Comment by kronusgarcia** [comment]
WORKED! THX ALOTE GI0

**Comment by raidensnake23** [comment]
i really don't understand much about all of this, but i've tired everything for the past 3 hours and still can't get it to work with wtfast. i don't now what i'm doing wrong. also, it works without wtfast.

**Comment by Gl0** [comment]
Generic walkthrough:
1. check raw sockets option enabled
2. incoming firewall rule - allow anything for meter .exe (make sure there is full path, without any macro like %Desktop%)
3. run meter as administrator
check that this setup is working at that moment, if not - recheck all 3 things
4. run any game vpn/proxy solution you like
5. run tera
6. launch resource monitor
7. find remote ip Tera.exe is connecting. For some solutions there would be public ip of vpn server (wtfast), for others (wowping, noping elite)- ipv4 loopback of local proxy (if it is loopback - use 127.0.0.1) .
8. open server-overrides.txt and add line 
`xx.xx.xx.xx NA vpn` 
Replace xx.xx.xx.xx with ip from (7) and NA with your region code.
9. if your vpn provider have different servers and you can connect to any of them - repeat points 4-8 for every remote server.
10. Use Casual as normal, but don't forget that you have to run it as admin every time.

**Comment by happikush** [comment]
Just to note that adding the Remote Addresses(yes all 3 addresses) used by WTFast also worked for me but I would need to add a new address in server-overrides.txt when I change server in WTFast.

Using `127.0.0.1 NA ssh-vpn` lets me switch WTFast servers without having to add new addresses in server-overrides.txt.

I tested it out too and worked wonders! I'm actually gonna stick with `127.0.0.1 NA ssh-vpn` in my server-overrides.txt.

@Gl0 much thanks again for that info!

**Comment by happikush** [comment]
Just to note that adding Remote Addresses used by WTFast also worked for me. The only downside being I need to add new addresses to server-overrides.txt if I change to a new server in WTFast.

Using `127.0.0.1 NA ssh-vpn` removes the necessity to keep adding new addresses to server-overrides.txt. I can change WTFast servers easily.

I tested it out and worked wonders! I'm actually gonna stick with `127.0.0.1 NA ssh-vpn` and recommend others to try that first.

@Gl0 much thanks again for that info!

**Comment by Gl0** [comment]
Btw, we may add some heuristics and parse some first received packets using both encryption variants against all known opcode lists to find correct opcode file and then wait for s_login to determine exact server and region. In that case we can add proxy for all regions in one string by default + ability to use meter with old db on minor updates, if new opcodes is already known from other regions.

**Comment by hsluoyz** [comment]
Hi.

You would like to try Npcap: https://github.com/nmap/npcap.

It's another fork of WinPcap with multiple new features.

**Comment by Gl0** [comment]
@hsluoyz , npcap can capture game traffic intercepted by local socksificator or some other transparent local encryptor before encryption take place? Like we doing it using raw sockets?

**Comment by SaitamaMucuta** [comment]
Good night, i tried all possible methods and i can't run NoPing Elite 15 with shinrameter, Shinrameter don't work. =(

**Comment by Gl0** [comment]
IDK what you've tried, but it's even have ShinraMeter.exe listed in configuration for Tera along with node.exe for tera-proxy (not sure what for, since meter doesn't connect to game servers). So I guess noping stuff at least know about all tera-related stuff.
Can't check how it's working, don't have EU or NA client/account, but seems it should work out of box with either raw sockets mode or via npcap loopback adapter. May be you need to switch routing mode in noping settings, there are 3 of them, not sure what's the difference.

**Comment by SaitamaMucuta** [comment]
i tried all possible IPs in task manager in the file server-overrides.txt. Buti don't understand this (Replace xx.xx.xx.xx with ip from (7) and NA with your region code.) Replace from 7 and my region code, i have no idea what is this.
thanks...

**Comment by Gl0** [comment]
You don't need to add anything there for noping.
